[build]
base = "/"
command = "rustup update stable && rustup default stable && cargo install cargo-make --locked --force && cargo make rust-docs"
publish = "docs/build/site"

[build.environment]
PKG_CONFIG_PATH = "/home/linuxbrew/.linuxbrew/lib/pkgconfig"
