---
services:
  relayer:
    build:
      context: ../../
      dockerfile: Dockerfile.development
    ports:
      - 8080:8080/tcp
    secrets:
      - api_key
      - webhook_signing_key
      - keystore_fund_passphrase
      - keystore_channel_001_passphrase
      - keystore_channel_002_passphrase
      - channels_admin_secret
    environment:
      REDIS_URL: redis://redis:6379
      RATE_LIMIT_REQUESTS_PER_SECOND: 10
      RATE_LIMIT_BURST: 50
      LOG_LEVEL: ${LOG_LEVEL}
      WEBHOOK_SIGNING_KEY: ${WEBHOOK_SIGNING_KEY}
      API_KEY: ${API_KEY}
      KEYSTORE_PASSPHRASE_FUND: ${KEYSTORE_PASSPHRASE_FUND}
      KEYSTORE_PASSPHRASE_CHANNEL_001: ${KEYSTORE_PASSPHRASE_CHANNEL_001}
      KEYSTORE_PASSPHRASE_CHANNEL_002: ${KEYSTORE_PASSPHRASE_CHANNEL_002}
      STELLAR_NETWORK: ${STELLAR_NETWORK}
      PLUGIN_ADMIN_SECRET: ${PLUGIN_ADMIN_SECRET}
      SOROBAN_RPC_URL: ${SOROBAN_RPC_URL}
      FUND_RELAYER_ID: ${FUND_RELAYER_ID}
      LOCK_TTL_SECONDS: ${LOCK_TTL_SECONDS}
    security_opt:
      - no-new-privileges
    networks:
      - relayer-network
      - metrics-network
    volumes:
      - ./config:/app/config/
      - ../../config/networks:/app/config/networks
      - ./channel:/app/plugins/channel
    depends_on:
      - redis
    restart: on-failure:5
  redis:
    image: redis:bookworm
    ports:
      - 6379:6379/tcp
    security_opt:
      - no-new-privileges
    volumes:
      - redis_data:/data
    command:
      - redis-server
      - --appendonly
      - 'yes'
      - --save
      - '60'
      - '1'
    networks:
      - relayer-network
      - metrics-network
    restart: on-failure:5
networks:
  metrics-network:
    internal: true
  relayer-network:
    driver: bridge
volumes:
  redis_data:
    driver: local
secrets:
  api_key:
    environment: API_KEY
  webhook_signing_key:
    environment: WEBHOOK_SIGNING_KEY
  keystore_fund_passphrase:
    environment: KEYSTORE_PASSPHRASE_FUND
  keystore_channel_001_passphrase:
    environment: KEYSTORE_PASSPHRASE_CHANNEL_001
  keystore_channel_002_passphrase:
    environment: KEYSTORE_PASSPHRASE_CHANNEL_002
  channels_admin_secret:
    environment: PLUGIN_ADMIN_SECRET
